/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDialogAbout: typeof import('./src/components/TheDialogAbout.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    TheViewDataEntryParsed: typeof import('./src/components/TheViewDataEntryParsed.vue')['default']
    TheViewEntries: typeof import('./src/components/TheViewEntries.vue')['default']
    TheViewJsonInput: typeof import('./src/components/TheViewJsonInput.vue')['default']
    TheViewJsonParsed: typeof import('./src/components/TheViewJsonParsed.vue')['default']
    TheViewListAuthors: typeof import('./src/components/TheViewListAuthors.vue')['default']
    TheViewListLanguages: typeof import('./src/components/TheViewListLanguages.vue')['default']
    TheViewListSources: typeof import('./src/components/TheViewListSources.vue')['default']
    TheViewListTags: typeof import('./src/components/TheViewListTags.vue')['default']
    TheViewSelectors: typeof import('./src/components/TheViewSelectors.vue')['default']
    TheViewTime: typeof import('./src/components/TheViewTime.vue')['default']
    TheViewTimeHeader: typeof import('./src/components/TheViewTimeHeader.vue')['default']
    TheWidgetSearch: typeof import('./src/components/TheWidgetSearch.vue')['default']
    VConnectedTreeNode: typeof import('./src/components/VObjectInspector/components/VConnectedTreeNode.vue')['default']
    VDataEntry: typeof import('./src/components/VDataEntry.vue')['default']
    VDialog: typeof import('./src/components/VDialog.vue')['default']
    VHistogram: typeof import('./src/components/VHistogram.vue')['default']
    VInteractive: typeof import('./src/components/VObjectInspector/stories/VInteractive.vue')['default']
    VMessage: typeof import('./src/components/VMessage.vue')['default']
    VMessages: typeof import('./src/components/VMessages.vue')['default']
    VObjectInspector: typeof import('./src/components/VObjectInspector/index.vue')['default']
    VObjectLabel: typeof import('./src/components/VObjectInspector/components/VObjectLabel.vue')['default']
    VObjectPreview: typeof import('./src/components/VObjectInspector/components/VObjectPreview.vue')['default']
    VObjectRootLabel: typeof import('./src/components/VObjectInspector/components/VObjectRootLabel.vue')['default']
    VObjectValue: typeof import('./src/components/VObjectInspector/components/VObjectValue.vue')['default']
    VSelector: typeof import('./src/components/VSelector.vue')['default']
    VTextFrequency: typeof import('./src/components/VTextFrequency.vue')['default']
    VTreeNode: typeof import('./src/components/VObjectInspector/components/VTreeNode.vue')['default']
    VTreeView: typeof import('./src/components/VObjectInspector/components/VTreeView.vue')['default']
    VViewListHeader: typeof import('./src/components/VViewListHeader.vue')['default']
  }
}
